name: Develop Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Instalando dependências
        run: yarn install

      - name: Build e testes
        run: |
          yarn build
          yarn test

      - name: Criando PR para main
        uses: peter-evans/create-pull-request@v5
        with:
          title: PR automático da branch develop para main
          branch: develop
          base: main
          commit-message: "PR automático da branch develop para main"
          labels: automate-pr
