name: Develop Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Instalando dependências
        run: yarn install

      - name: Build e teste
        run: |
          yarn build
          yarn test

  deploy:
    runs-on: ubuntu-latest
    name: Deploy na AWS

    needs: build_and_test

    steps:
      - name: Configurando AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy na AWS
        run: deploy.sh

      - name: Deploy realizado com sucesso
        if: success()
        run: echo 'Deployment successful!'