name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build e testes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.0'

      - name: Instalando dependências
        run: yarn install

      - name: Build e testes
        run: |
          yarn build
          yarn test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=gabsribeiro
            -Dsonar.projectKey=repo-teste-tc-producao

          
          
          
          
